seo:
  description: "Build your next web project with the official Bootstrap starter for Hyas."
  generate:
    title: true
    meta: true
    twitter: true
    og: true
    jsonld:
      article: true
      breadcrumbs: true
  title_tag:
    separator: "|"
    home_text: "Bootstrap Starter"
  og_article_types: [post, posts, blog, news, article, articles, event, events, course, courses]
  jsonld_article_types: [article, articles]
  jsonld_news_article_types: [news, updates]
  jsonld_blog_posting_types: [post, posts, blog]
  image: "/images/kris-mikael-krister-aGihPIbrtVE-unsplash.jpg" 
  private: false
